version: '2'
services:
  prefect:
    build: .
    ports:
      - "4200:4200"
    env_file: .env
    depends_on:
      - db
      - solr
    volumes:
      - data:/opt/metadata-qa-ddb-data/
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=ddbkultur
      - MYSQL_USER=ddbkultur
      - MYSQL_PASSWORD=ddbkultur
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  solr:
    image: bitnami/solr:9.1.1
    restart: always
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/bitnami
networks:
  webnet:
volumes:
  data:
  mysql_data:
  solr_data:
