version: '2'
services:
  data:
    build: .
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - db
      - solr
    volumes:
      - datavolume:/opt/metadata-qa-ddb/data/
  db:
    image: mariadb:10.10
    restart: always
    env_file: .env
    ports:
      - "3306:3306"
  solr:
    image: solr:9.1.1
    restart: always
    ports:
      - "8983:8983"
networks:
  webnet:
volumes:
  datavolume:
